In [3]:
import numpy as np
import torch
print(torch.__version__)

2.0.1+cu117


In [4]:
x1 = [[1,1],[2,2]]
print("Type of data:{}".format(type(x1)))
print(x1)
x1 = np.array(x1)
print("Type of data:{}".format(type(x1)))
print(x1)

Type of data:<class 'list'>
[[1, 1], [2, 2]]
Type of data:<class 'numpy.ndarray'>
[[1 1]
 [2 2]]


In [6]:
x_tensor = torch.tensor(x1)
print("Type of data:{}".format(type(x_tensor)))
print(x_tensor)
x_tensor2 = torch.from_numpy(x1)
print("Type of data:{}".format(type(x_tensor2)))
print(x_tensor2)

Type of data:<class 'torch.Tensor'>
tensor([[1, 1],
        [2, 2]])
Type of data:<class 'torch.Tensor'>
tensor([[1, 1],
        [2, 2]])


In [7]:
print(torch.rand(2,2))

tensor([[0.8306, 0.5361],
        [0.9034, 0.9569]])


In [8]:
arr1 = torch.tensor([1,2,4])
arr2 = torch.tensor([2,3,4])
print(torch.dot(arr1,arr2))

tensor(24)


In [11]:
arr1 = torch.tensor([1,2,4]).reshape(1,-1)
arr2 = torch.tensor([2,3,4]).reshape(-1,1)
print(arr1.shape,arr2.shape)
print(torch.mm(arr2,arr1))

torch.Size([1, 3]) torch.Size([3, 1])
tensor([[ 2,  4,  8],
        [ 3,  6, 12],
        [ 4,  8, 16]])
